export default {
    FOO_BAR: "FOO_BAR",
    REQUEST_RIDE: "REQUEST_RIDE",
    REQUEST_RIDE_FULFILLED:"REQUEST_RIDE_FULFILLED",
    CANCEL_RIDE: "CANCEL_RIDE",
    CANCEL_RIDE_FULFILLED: "CANCEL_RIDE_FULFILLED"
}

export const rideStatus = {
    DEFAULT: "DEFAULT",
    REQUESTED: "REQUESTED",
    CANCELLED:"CANCELLED"
};

